version: 0.2

phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 593777010364.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - npm run lint
      - npm test
      - npm run build
      - docker build -t orders-api:latest .
      - docker tag orders-api:latest 593777010364.dkr.ecr.us-east-2.amazonaws.com/orders-api:latest
      - docker push 593777010364.dkr.ecr.us-east-2.amazonaws.com/orders-api:latest