version: 0.2

phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 593777010364.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - npm run lint
      - npm test
      - npm run build
      - docker build -t orders-api:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag orders-api:$CODEBUILD_RESOLVED_SOURCE_VERSION 593777010364.dkr.ecr.us-east-2.amazonaws.com/orders-api:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 593777010364.dkr.ecr.us-east-2.amazonaws.com/orders-api:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '[{"name":"Main","imageUri":"593777010364.dkr.ecr.us-east-2.amazonaws.com/orders-api:%s"}]' "$CODEBUILD_RESOLVED_SOURCE_VERSION" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json